Title : Vinoth Rajendran
logo: https://pbs.twimg.com/profile_images/1148964968097705984/2AeQzauu_400x400.jpg
description: Vinoth Rajendran | Speaker | Technical Specialist | UWP | Bot Framework | Xamarin
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
