Title : Vinoth Rajendran
logo: https://pbs.twimg.com/profile_images/1148964968097705984/2AeQzauu_400x400.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
